apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: backend
          image: davidaris/app-back:57acfd9f6dfda6cba93ce6fd50fe5ca3884cc1fe
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
