apiVersion: v1
kind: Service
metadata:
  name: back-svc
  namespace: ingress-nginx
spec:
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
