apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: frontend
          image: davidaris/app-front:3fc7911dca40efabc91a769627984581550e4402
          ports:
            - containerPort: 3000
