apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: frontend
          image: davidaris/app-front:36e6295ea6d15346f8eff68771e656229a2283ba
          ports:
            - containerPort: 3000
